services:
  - type: web
    name: bencyn-susu-api
    env: python
    buildCommand: chmod +x backend/build.sh && backend/build.sh
    startCommand: cd backend && gunicorn bencyn_susu.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bencyn-susu-db
          property: connectionString

databases:
  - name: bencyn-susu-db
    databaseName: bencyn_susu
    user: bencyn_susu_user

